/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./src/components/Modal/src/BasicModal.vue')['default']
    copy: typeof import('./src/components/loadingImg/index copy.vue')['default']
    Index2: typeof import('./src/components/loadingImg/index2.vue')['default']
    LoadingImg: typeof import('./src/components/loadingImg/index.vue')['default']
    MyEcharts: typeof import('./src/components/echarts/myEcharts.vue')['default']
    MyTransition: typeof import('./src/components/myTransition/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBack: typeof import('./src/components/topBack/index.vue')['default']
  }
}
