/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    LoadingImg: typeof import('./../src/components/loadingImg/index.vue')['default']
    MyEcharts: typeof import('./../src/components/echarts/myEcharts.vue')['default']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
