/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    LoadingImg: typeof import('./../src/components/loadingImg/index.vue')['default']
    MyEcharts: typeof import('./../src/components/echarts/myEcharts.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    NutCell: typeof import('@nutui/nutui')['Cell']
    NutCellGroup: typeof import('@nutui/nutui')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui')['CheckboxGroup']
    NutCircleProgress: typeof import('@nutui/nutui')['CircleProgress']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutDialog: typeof import('@nutui/nutui')['Dialog']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutImage: typeof import('@nutui/nutui')['Image']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutOverlay: typeof import('@nutui/nutui')['Overlay']
    NutPicker: typeof import('@nutui/nutui')['Picker']
    NutPopup: typeof import('@nutui/nutui')['Popup']
    NutRadio: typeof import('@nutui/nutui')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui')['RadioGroup']
    NutRange: typeof import('@nutui/nutui')['Range']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutSearchbar: typeof import('@nutui/nutui')['Searchbar']
    NutStep: typeof import('@nutui/nutui')['Step']
    NutSteps: typeof import('@nutui/nutui')['Steps']
    NutSticky: typeof import('@nutui/nutui')['Sticky']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutUploader: typeof import('@nutui/nutui')['Uploader']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBack: typeof import('./../src/components/topBack/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPasswordInput: typeof import('vant/es')['PasswordInput']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
