/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BasicModal: typeof import('./../src/components/Modal/src/BasicModal.vue')['default']
    LoadingImg: typeof import('./../src/components/loadingImg/index.vue')['default']
    MyEcharts: typeof import('./../src/components/echarts/myEcharts.vue')['default']
    NutCol: typeof import('@nutui/nutui')['Col']
    NutEmpty: typeof import('@nutui/nutui')['Empty']
    NutGrid: typeof import('@nutui/nutui')['Grid']
    NutGridItem: typeof import('@nutui/nutui')['GridItem']
    NutInfiniteLoading: typeof import('@nutui/nutui')['InfiniteLoading']
    NutInput: typeof import('@nutui/nutui')['Input']
    NutNoticebar: typeof import('@nutui/nutui')['Noticebar']
    NutRow: typeof import('@nutui/nutui')['Row']
    NutStep: typeof import('@nutui/nutui')['Step']
    NutSteps: typeof import('@nutui/nutui')['Steps']
    NutSwiper: typeof import('@nutui/nutui')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui')['SwiperItem']
    NutTabbar: typeof import('@nutui/nutui')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui')['TabPane']
    NutTabs: typeof import('@nutui/nutui')['Tabs']
    NutTag: typeof import('@nutui/nutui')['Tag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBack: typeof import('./../src/components/topBack/index.vue')['default']
  }
}
