/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.19.4
// source: prox.proto

/* eslint-disable */
// @ts-nocheck

const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.proto = require('./prox_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ServiceClient = function (hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');
};

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ServicePromiseClient = function (hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxPingRequest,
 *   !proto.proto.ProxPingResponse>}
 */
const methodDescriptor_Service_Ping = new grpc.web.MethodDescriptor(
  '/proto.Service/Ping',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxPingRequest,
  proto.proto.ProxPingResponse,
  /**
   * @param {!proto.proto.ProxPingRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxPingResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxPingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxPingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxPingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.ping = function (request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ + '/proto.Service/Ping', request, metadata || {}, methodDescriptor_Service_Ping, callback);
};

/**
 * @param {!proto.proto.ProxPingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxPingResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.ping = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/Ping', request, metadata || {}, methodDescriptor_Service_Ping);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxPinReq,
 *   !proto.proto.ProxPinResp>}
 */
const methodDescriptor_Service_Pin = new grpc.web.MethodDescriptor(
  '/proto.Service/Pin',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxPinReq,
  proto.proto.ProxPinResp,
  /**
   * @param {!proto.proto.ProxPinReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxPinResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxPinReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxPinResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxPinResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.pin = function (request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ + '/proto.Service/Pin', request, metadata || {}, methodDescriptor_Service_Pin, callback);
};

/**
 * @param {!proto.proto.ProxPinReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxPinResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.pin = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/Pin', request, metadata || {}, methodDescriptor_Service_Pin);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.GetPeerIdInfoReq,
 *   !proto.proto.GetPeerIDReply>}
 */
const methodDescriptor_Service_GetPeerIdInfo = new grpc.web.MethodDescriptor(
  '/proto.Service/GetPeerIdInfo',
  grpc.web.MethodType.UNARY,
  proto.proto.GetPeerIdInfoReq,
  proto.proto.GetPeerIDReply,
  /**
   * @param {!proto.proto.GetPeerIdInfoReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.GetPeerIDReply.deserializeBinary,
);

/**
 * @param {!proto.proto.GetPeerIdInfoReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.GetPeerIDReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.GetPeerIDReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getPeerIdInfo = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/GetPeerIdInfo',
    request,
    metadata || {},
    methodDescriptor_Service_GetPeerIdInfo,
    callback,
  );
};

/**
 * @param {!proto.proto.GetPeerIdInfoReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.GetPeerIDReply>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.getPeerIdInfo = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/GetPeerIdInfo',
    request,
    metadata || {},
    methodDescriptor_Service_GetPeerIdInfo,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxPutObjectReq,
 *   !proto.proto.ProxMultipartCreateResp>}
 */
const methodDescriptor_Service_NewMultipartObject = new grpc.web.MethodDescriptor(
  '/proto.Service/NewMultipartObject',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxPutObjectReq,
  proto.proto.ProxMultipartCreateResp,
  /**
   * @param {!proto.proto.ProxPutObjectReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxMultipartCreateResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxPutObjectReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxMultipartCreateResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxMultipartCreateResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.newMultipartObject = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/NewMultipartObject',
    request,
    metadata || {},
    methodDescriptor_Service_NewMultipartObject,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxPutObjectReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxMultipartCreateResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.newMultipartObject = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/NewMultipartObject',
    request,
    metadata || {},
    methodDescriptor_Service_NewMultipartObject,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxCompleteMultipartReq,
 *   !proto.proto.ProxCompleteMultipartResp>}
 */
const methodDescriptor_Service_CompleteMultipart = new grpc.web.MethodDescriptor(
  '/proto.Service/CompleteMultipart',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxCompleteMultipartReq,
  proto.proto.ProxCompleteMultipartResp,
  /**
   * @param {!proto.proto.ProxCompleteMultipartReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxCompleteMultipartResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxCompleteMultipartReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxCompleteMultipartResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxCompleteMultipartResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.completeMultipart = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/CompleteMultipart',
    request,
    metadata || {},
    methodDescriptor_Service_CompleteMultipart,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxCompleteMultipartReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxCompleteMultipartResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.completeMultipart = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/CompleteMultipart',
    request,
    metadata || {},
    methodDescriptor_Service_CompleteMultipart,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxListUploadReq,
 *   !proto.proto.ProxListMultipartUploadResponse>}
 */
const methodDescriptor_Service_ListMultipart = new grpc.web.MethodDescriptor(
  '/proto.Service/ListMultipart',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxListUploadReq,
  proto.proto.ProxListMultipartUploadResponse,
  /**
   * @param {!proto.proto.ProxListUploadReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxListMultipartUploadResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxListUploadReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxListMultipartUploadResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxListMultipartUploadResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.listMultipart = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/ListMultipart',
    request,
    metadata || {},
    methodDescriptor_Service_ListMultipart,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxListUploadReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxListMultipartUploadResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.listMultipart = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/ListMultipart',
    request,
    metadata || {},
    methodDescriptor_Service_ListMultipart,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxListPartsReq,
 *   !proto.proto.ProxListPartsResponse>}
 */
const methodDescriptor_Service_ListObjectParts = new grpc.web.MethodDescriptor(
  '/proto.Service/ListObjectParts',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxListPartsReq,
  proto.proto.ProxListPartsResponse,
  /**
   * @param {!proto.proto.ProxListPartsReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxListPartsResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxListPartsReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxListPartsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxListPartsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.listObjectParts = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/ListObjectParts',
    request,
    metadata || {},
    methodDescriptor_Service_ListObjectParts,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxListPartsReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxListPartsResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.listObjectParts = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/ListObjectParts',
    request,
    metadata || {},
    methodDescriptor_Service_ListObjectParts,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxListObjectsReq,
 *   !proto.proto.ProxListObjectsResp>}
 */
const methodDescriptor_Service_ListObjects = new grpc.web.MethodDescriptor(
  '/proto.Service/ListObjects',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxListObjectsReq,
  proto.proto.ProxListObjectsResp,
  /**
   * @param {!proto.proto.ProxListObjectsReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxListObjectsResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxListObjectsReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxListObjectsResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxListObjectsResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.listObjects = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/ListObjects',
    request,
    metadata || {},
    methodDescriptor_Service_ListObjects,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxListObjectsReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxListObjectsResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.listObjects = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/ListObjects',
    request,
    metadata || {},
    methodDescriptor_Service_ListObjects,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxGetRequest,
 *   !proto.proto.ProxGetResponse>}
 */
const methodDescriptor_Service_GetObject = new grpc.web.MethodDescriptor(
  '/proto.Service/GetObject',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ProxGetRequest,
  proto.proto.ProxGetResponse,
  /**
   * @param {!proto.proto.ProxGetRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxGetResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxGetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxGetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getObject = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/GetObject',
    request,
    metadata || {},
    methodDescriptor_Service_GetObject,
  );
};

/**
 * @param {!proto.proto.ProxGetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxGetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServicePromiseClient.prototype.getObject = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/GetObject',
    request,
    metadata || {},
    methodDescriptor_Service_GetObject,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxGetRequests,
 *   !proto.proto.ProxGetResponse>}
 */
const methodDescriptor_Service_GetObjects = new grpc.web.MethodDescriptor(
  '/proto.Service/GetObjects',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ProxGetRequests,
  proto.proto.ProxGetResponse,
  /**
   * @param {!proto.proto.ProxGetRequests} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxGetResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxGetRequests} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxGetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getObjects = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/GetObjects',
    request,
    metadata || {},
    methodDescriptor_Service_GetObjects,
  );
};

/**
 * @param {!proto.proto.ProxGetRequests} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxGetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServicePromiseClient.prototype.getObjects = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/GetObjects',
    request,
    metadata || {},
    methodDescriptor_Service_GetObjects,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxSearchRequest,
 *   !proto.proto.ProxSearchResponse>}
 */
const methodDescriptor_Service_SearchObject = new grpc.web.MethodDescriptor(
  '/proto.Service/SearchObject',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ProxSearchRequest,
  proto.proto.ProxSearchResponse,
  /**
   * @param {!proto.proto.ProxSearchRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxSearchResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxSearchRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxSearchResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.searchObject = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/SearchObject',
    request,
    metadata || {},
    methodDescriptor_Service_SearchObject,
  );
};

/**
 * @param {!proto.proto.ProxSearchRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxSearchResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ServicePromiseClient.prototype.searchObject = function (request, metadata) {
  return this.client_.serverStreaming(
    this.hostname_ + '/proto.Service/SearchObject',
    request,
    metadata || {},
    methodDescriptor_Service_SearchObject,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxFindRequest,
 *   !proto.proto.ProxObjects>}
 */
const methodDescriptor_Service_FindObjects = new grpc.web.MethodDescriptor(
  '/proto.Service/FindObjects',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxFindRequest,
  proto.proto.ProxObjects,
  /**
   * @param {!proto.proto.ProxFindRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxObjects.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxFindRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxObjects)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxObjects>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.findObjects = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/FindObjects',
    request,
    metadata || {},
    methodDescriptor_Service_FindObjects,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxFindRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxObjects>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.findObjects = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/FindObjects',
    request,
    metadata || {},
    methodDescriptor_Service_FindObjects,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxGetRequest,
 *   !proto.proto.ProxObject>}
 */
const methodDescriptor_Service_GetObjectInfo = new grpc.web.MethodDescriptor(
  '/proto.Service/GetObjectInfo',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxGetRequest,
  proto.proto.ProxObject,
  /**
   * @param {!proto.proto.ProxGetRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxObject.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxGetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxObject)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxObject>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getObjectInfo = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/GetObjectInfo',
    request,
    metadata || {},
    methodDescriptor_Service_GetObjectInfo,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxGetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxObject>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.getObjectInfo = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/GetObjectInfo',
    request,
    metadata || {},
    methodDescriptor_Service_GetObjectInfo,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxDeleteObjectReq,
 *   !proto.proto.ProxDeleteResp>}
 */
const methodDescriptor_Service_DeleteObject = new grpc.web.MethodDescriptor(
  '/proto.Service/DeleteObject',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxDeleteObjectReq,
  proto.proto.ProxDeleteResp,
  /**
   * @param {!proto.proto.ProxDeleteObjectReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxDeleteResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxDeleteObjectReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxDeleteResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxDeleteResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.deleteObject = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/DeleteObject',
    request,
    metadata || {},
    methodDescriptor_Service_DeleteObject,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxDeleteObjectReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxDeleteResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.deleteObject = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/DeleteObject',
    request,
    metadata || {},
    methodDescriptor_Service_DeleteObject,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxRequestSummaryIds,
 *   !proto.proto.ProxSummaryInfos>}
 */
const methodDescriptor_Service_SummaryInfo = new grpc.web.MethodDescriptor(
  '/proto.Service/SummaryInfo',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxRequestSummaryIds,
  proto.proto.ProxSummaryInfos,
  /**
   * @param {!proto.proto.ProxRequestSummaryIds} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxSummaryInfos.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxRequestSummaryIds} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxSummaryInfos)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxSummaryInfos>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.summaryInfo = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/SummaryInfo',
    request,
    metadata || {},
    methodDescriptor_Service_SummaryInfo,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxRequestSummaryIds} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxSummaryInfos>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.summaryInfo = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/SummaryInfo',
    request,
    metadata || {},
    methodDescriptor_Service_SummaryInfo,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxRenameObject,
 *   !proto.proto.ProxRenameObjectResp>}
 */
const methodDescriptor_Service_RenameObjects = new grpc.web.MethodDescriptor(
  '/proto.Service/RenameObjects',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxRenameObject,
  proto.proto.ProxRenameObjectResp,
  /**
   * @param {!proto.proto.ProxRenameObject} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxRenameObjectResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxRenameObject} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxRenameObjectResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxRenameObjectResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.renameObjects = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/RenameObjects',
    request,
    metadata || {},
    methodDescriptor_Service_RenameObjects,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxRenameObject} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxRenameObjectResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.renameObjects = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/RenameObjects',
    request,
    metadata || {},
    methodDescriptor_Service_RenameObjects,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxTimeLine,
 *   !proto.proto.ProxTimeLineResp>}
 */
const methodDescriptor_Service_GetTimeLine = new grpc.web.MethodDescriptor(
  '/proto.Service/GetTimeLine',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxTimeLine,
  proto.proto.ProxTimeLineResp,
  /**
   * @param {!proto.proto.ProxTimeLine} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxTimeLineResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxTimeLine} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxTimeLineResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxTimeLineResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getTimeLine = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/GetTimeLine',
    request,
    metadata || {},
    methodDescriptor_Service_GetTimeLine,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxTimeLine} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxTimeLineResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.getTimeLine = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/GetTimeLine',
    request,
    metadata || {},
    methodDescriptor_Service_GetTimeLine,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxPresignedURL,
 *   !proto.proto.ProxPresignedURLResp>}
 */
const methodDescriptor_Service_GetPreSigned = new grpc.web.MethodDescriptor(
  '/proto.Service/GetPreSigned',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxPresignedURL,
  proto.proto.ProxPresignedURLResp,
  /**
   * @param {!proto.proto.ProxPresignedURL} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxPresignedURLResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxPresignedURL} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxPresignedURLResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxPresignedURLResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.getPreSigned = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/GetPreSigned',
    request,
    metadata || {},
    methodDescriptor_Service_GetPreSigned,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxPresignedURL} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxPresignedURLResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.getPreSigned = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/GetPreSigned',
    request,
    metadata || {},
    methodDescriptor_Service_GetPreSigned,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxFileInfo,
 *   !proto.proto.ProxTouchResp>}
 */
const methodDescriptor_Service_TouchFile = new grpc.web.MethodDescriptor(
  '/proto.Service/TouchFile',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxFileInfo,
  proto.proto.ProxTouchResp,
  /**
   * @param {!proto.proto.ProxFileInfo} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxTouchResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxFileInfo} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxTouchResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxTouchResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.touchFile = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/TouchFile',
    request,
    metadata || {},
    methodDescriptor_Service_TouchFile,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxFileInfo} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxTouchResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.touchFile = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/TouchFile', request, metadata || {}, methodDescriptor_Service_TouchFile);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxChatReq,
 *   !proto.proto.ProxChatResponse>}
 */
const methodDescriptor_Service_Chat = new grpc.web.MethodDescriptor(
  '/proto.Service/Chat',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxChatReq,
  proto.proto.ProxChatResponse,
  /**
   * @param {!proto.proto.ProxChatReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxChatResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxChatReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxChatResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxChatResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.chat = function (request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ + '/proto.Service/Chat', request, metadata || {}, methodDescriptor_Service_Chat, callback);
};

/**
 * @param {!proto.proto.ProxChatReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxChatResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.chat = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/Chat', request, metadata || {}, methodDescriptor_Service_Chat);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxKNReq,
 *   !proto.proto.ProxKNResponse>}
 */
const methodDescriptor_Service_Knowledge = new grpc.web.MethodDescriptor(
  '/proto.Service/Knowledge',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxKNReq,
  proto.proto.ProxKNResponse,
  /**
   * @param {!proto.proto.ProxKNReq} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxKNResponse.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxKNReq} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxKNResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxKNResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.knowledge = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/Knowledge',
    request,
    metadata || {},
    methodDescriptor_Service_Knowledge,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxKNReq} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxKNResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.knowledge = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/Knowledge', request, metadata || {}, methodDescriptor_Service_Knowledge);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxCredRequest,
 *   !proto.proto.ProxCredResp>}
 */
const methodDescriptor_Service_GenerateCred = new grpc.web.MethodDescriptor(
  '/proto.Service/GenerateCred',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxCredRequest,
  proto.proto.ProxCredResp,
  /**
   * @param {!proto.proto.ProxCredRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxCredResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxCredRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxCredResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxCredResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.generateCred = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/GenerateCred',
    request,
    metadata || {},
    methodDescriptor_Service_GenerateCred,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxCredRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxCredResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.generateCred = function (request, metadata) {
  return this.client_.unaryCall(
    this.hostname_ + '/proto.Service/GenerateCred',
    request,
    metadata || {},
    methodDescriptor_Service_GenerateCred,
  );
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxGetCredRequest,
 *   !proto.proto.ProxCredsList>}
 */
const methodDescriptor_Service_ListCreds = new grpc.web.MethodDescriptor(
  '/proto.Service/ListCreds',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxGetCredRequest,
  proto.proto.ProxCredsList,
  /**
   * @param {!proto.proto.ProxGetCredRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxCredsList.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxGetCredRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxCredsList)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxCredsList>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.listCreds = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/ListCreds',
    request,
    metadata || {},
    methodDescriptor_Service_ListCreds,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxGetCredRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxCredsList>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.listCreds = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/ListCreds', request, metadata || {}, methodDescriptor_Service_ListCreds);
};

/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ProxCredRequest,
 *   !proto.proto.ProxCredResp>}
 */
const methodDescriptor_Service_DeleteCred = new grpc.web.MethodDescriptor(
  '/proto.Service/DeleteCred',
  grpc.web.MethodType.UNARY,
  proto.proto.ProxCredRequest,
  proto.proto.ProxCredResp,
  /**
   * @param {!proto.proto.ProxCredRequest} request
   * @return {!Uint8Array}
   */
  function (request) {
    return request.serializeBinary();
  },
  proto.proto.ProxCredResp.deserializeBinary,
);

/**
 * @param {!proto.proto.ProxCredRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.ProxCredResp)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ProxCredResp>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ServiceClient.prototype.deleteCred = function (request, metadata, callback) {
  return this.client_.rpcCall(
    this.hostname_ + '/proto.Service/DeleteCred',
    request,
    metadata || {},
    methodDescriptor_Service_DeleteCred,
    callback,
  );
};

/**
 * @param {!proto.proto.ProxCredRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.ProxCredResp>}
 *     Promise that resolves to the response
 */
proto.proto.ServicePromiseClient.prototype.deleteCred = function (request, metadata) {
  return this.client_.unaryCall(this.hostname_ + '/proto.Service/DeleteCred', request, metadata || {}, methodDescriptor_Service_DeleteCred);
};

module.exports = proto.proto;
